version: "3.8"

networks:
  backend_network:

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - backend_network

  mongo:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    networks:
      - backend_network

volumes:
  mongo-data:
